// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebShop.Data.DbContext;

namespace TestWebShop.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210116085114_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TestWebShop.Data.Entities.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Articul")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Articul");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Currency");

                    b.Property<string>("GoodTypeCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("GoodTypeCode");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("ProducerCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ProducerCode");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("GoodTypeCode");

                    b.HasIndex("ProducerCode");

                    b.ToTable("good");
                });

            modelBuilder.Entity("TestWebShop.Data.Entities.GoodType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Code");

                    b.ToTable("goodtype");
                });

            modelBuilder.Entity("TestWebShop.Data.Entities.Producer", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Code");

                    b.ToTable("producer");
                });

            modelBuilder.Entity("TestWebShop.Data.Entities.Good", b =>
                {
                    b.HasOne("TestWebShop.Data.Entities.GoodType", "GoodTypes")
                        .WithMany("Goods")
                        .HasForeignKey("GoodTypeCode");

                    b.HasOne("TestWebShop.Data.Entities.Producer", "Producers")
                        .WithMany("Goods")
                        .HasForeignKey("ProducerCode");

                    b.Navigation("GoodTypes");

                    b.Navigation("Producers");
                });

            modelBuilder.Entity("TestWebShop.Data.Entities.GoodType", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("TestWebShop.Data.Entities.Producer", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
